### ISSUE TITLE
REVIEW: Revised toggle/dropdown pattern

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-pattern-library#6]
@sophshep & @middle8media 

Could one or both of you find some time in the next week to review my revision to the way we handle toggle/dropdown patterns? I've staged it in [a new branch called "toggle-pattern."](https://github.com/ushahidi/platform-pattern-library/tree/toggle-pattern)

The revision centers around one JavaScript file, [toggle.js](https://github.com/ushahidi/platform-pattern-library/blob/toggle-pattern/assets/js/custom/toggle.js), and then a convention for handling the styling of patterns that use it.

Here's the problem it solves: Toggling the visibility of something in our current (production) implementation depends on a very specific convention for applying class names to elements with _a uniform relationship to one another_. It looks for anything with the class name `toggle-content-trigger` and assumes its parent has a sibling with the class name `toggle-content`. It listens for clicks on the "trigger" element, and toggles the `visible` class on itself and its parent's `toggle-content` sibling.

As applied in CSS, it also assumes anything with the class name `toggle-content` is hidden by default.

So the problem that I encountered with this was two-fold:

1. It has a very strict requirement around the relationship between the toggle trigger and its target.
2. It made it very difficult to handle exceptions to the notion that the target be hidden by default.

I encountered the latter problem when trying to implement a toggle/dropdown control inside [the "post detail"](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-detail.html) layout's sidebar. The dropdown was always visible by default, even though the pattern calls for the dropdown menu to be hidden by default. And I discovered that the reason or this was we had applied [a layout-level style](https://github.com/ushahidi/platform-pattern-library/blob/85711df1dacf8796f6e29e4561727cb19489ad99/assets/sass/2_fragments/_actions.scss#L66-L72) that dictated that any toggle targets within a post detail screen be displayed on larger screens -- when, in fact, it was really only intended to affect [one specific toggling pattern](https://github.com/ushahidi/platform-pattern-library/blob/85711df1dacf8796f6e29e4561727cb19489ad99/pattern-library/5_layouts/post-detail.html#L45-L64).

So, like the problem, my proposed solution is two-fold:

1. Provide a convention that's flexible to the relationship between the toggle trigger and its target.
2. Separate presentation (e.g. visibility) from the toggle interaction.

Regarding the flexibility piece, **toggle.js** now works like this:

* It looks for any elements with the attribute `data-toggle` and assumes it's a toggle trigger.
* It looks for any elements with an `id` whose value matches that of the trigger. If it can't find one, it looks for the next sibling with a class name matching the trigger's `data-toggle` value. Whichever one it finds, it'll assume that's the toggle target.
* It checks to see if the target is visible (dictated by that specific pattern's CSS). If it is, it adds the class name `active` to both the trigger and target elements.
* It listens for clicks on the trigger and, when clicked, toggles the 'active' class appropriately on both the trigger and target.

In practice, this means that we can take any pattern (e.g. a heading and some text below it, or a label and an input), no matter how it's already structured, and apply a toggle interaction to it. Just apply the `data-toggle` attribute to the trigger and, depending on the pattern, either apply a matching `id` (to any element) or class name (to a sibling) to dictate its target.

Then, with each pattern's CSS, we can dictate how it should be presented at any given screen size. 

So, for example, [the aforementioned post detail's "Options" pattern](https://github.com/ushahidi/platform-pattern-library/blob/85711df1dacf8796f6e29e4561727cb19489ad99/pattern-library/5_layouts/post-detail.html#L40-L65) might by default have its trigger visible, and its target hidden: 

![image](https://cloud.githubusercontent.com/assets/1136279/10322213/66f45f32-6c42-11e5-843a-716f62bf8515.png)

But on larger screens, we might want that pattern to always hide the trigger and always display the target:

![image](https://cloud.githubusercontent.com/assets/1136279/10322227/7c4b43be-6c42-11e5-9714-85c306f9d0d4.png)

Yet, in another example, [the "Collections" control](https://github.com/ushahidi/platform-pattern-library/blob/toggle-pattern/pattern-library/partials/_add-to-collection.html), we have an embedded "Create collection" toggle target that, by default, is always visible (no matter the screen size). And its target is, by default always hidden:

![image](https://cloud.githubusercontent.com/assets/1136279/10322257/958c07a0-6c42-11e5-8bf5-41eea735f64b.png)

But when you click the trigger and make them "active," the trigger is hidden:

![image](https://cloud.githubusercontent.com/assets/1136279/10322268/a067ec84-6c42-11e5-8c1a-6e22471e14fb.png)

That leaves the more typical, conventional example of a trigger that is always visible, and a target that's hidden by default: 

![image](https://cloud.githubusercontent.com/assets/1136279/10322301/be74754e-6c42-11e5-8789-4084ea8c4d98.png)

And, predictably, its visibility is toggled upon clicking the trigger:

![image](https://cloud.githubusercontent.com/assets/1136279/10322320/d9b153f4-6c42-11e5-9a51-0f85bd58ca77.png)

All of these are accounted for (I believe) with this approach.

So my burning question in your review is: Does this break anything? Is it too complex? Does it bother you?

Let me know, and let's get this branch right so we can pull some sort of improvement into master.

**Comment by sophshep** [comment]
I think this is complex enough that we should both review. I can take a look tonight or tomorrow.

**Comment by middle8media** [comment]
@brandonrosage first of all, great work. Your ability to handle the most complex patterns always amazes me, and with such conviction and speed.

Based on my quick testing of the three elements above and looking at code ...

> Does this break anything?
This animation feels distracting.
![screen capture on 2015-10-07 at 11-53-18](https://cloud.githubusercontent.com/assets/1033332/10343066/0ef3a272-6cea-11e5-8096-7f8c0388b218.gif)

> Is it too complex?

No. Feels right to me.

> Does it bother you?

Not at all.

**Comment by brandonrosage** [comment]
Thanks, @middle8media. I just pushed a revision to the user toggle/dropdown that dials down the animation. Better?

![Interaction example](http://d.pr/i/17iwb+)

**Comment by middle8media** [comment]
@brandonrosage much.

**Comment by sophshep** [comment]
The js here looks great, and thank you for the awesome explanation! We should link to this issue from within the PL since it's public and so helpful to explain how it works.

A few little buggy things/places that still need to be updated:

* I've noticed that the home, list view layout gets a bit broken on larger screens:
![image](https://cloud.githubusercontent.com/assets/527589/10374459/2c2e4c34-6da8-11e5-8b00-080d8ef4e5d7.png)

* It is also broken on the dropdown button on the fragments page of the PL:
![image](https://cloud.githubusercontent.com/assets/527589/10374524/78f47782-6da8-11e5-9bed-cd7192dbd15f.png)

* and on the [settings listings pattern](http://localhost:8080/assets/html/3_modules/#pl-pattern-settings-listings)

* and the [step list (small screen) in the PL](http://localhost:8080/assets/html/3_modules/#pl-pattern-step-list) and the [step list on create post layout](http://localhost:8080/assets/html/5_layouts/create-post.html)

Let me know if I can help fix these in anyway. We could always split them into their own issues to divide and conquer.

**Comment by brandonrosage** [comment]
@sophshep Should be fixed. Confirm and we'll pass it on to the product for implementation.

**Comment by sophshep** [comment]
I'm still seeing some formatting brokenness on the list view layout. It should have borders on the left & right and have every other listing be light gray (using the "zebra" extend)

![image](https://cloud.githubusercontent.com/assets/527589/10645128/bbedafa6-77f1-11e5-9190-25651723f971.png)

And also on the small screen of the step list pattern (when it collapses into a dropdown), which shows up [in the PL](http://localhost:8080/assets/html/3_modules/#pl-pattern-step-list) and on the [create post layout](http://localhost:8080/assets/html/5_layouts/create-post.html)

**Comment by brandonrosage** [comment]
Fixed the list summary and `.step-list' implementation.

What about now, @sophshep?

**Comment by sophshep** [comment]
Looks great!

**Comment by brandonrosage** [comment]
NOTE: I've merged the *toggle-pattern* branch into *gh-pages.*
